### PR TITLE
Fix axios adapter issue

### PR DESCRIPTION
**Pull request by mateuszmlc**

### CODE REVIEW

**Comment by mateuszmlc** [comment]
Works on CRA, breaks on next.js:
Screenshot 2023-02-04 at 13 26 23

**Comment by mateuszmlc** [comment]
Fixed the next.js error in https://github.com/polybase/polybase-ts/pull/76/commits/69813f790858fb342e4b375d84b41a25c602228a

**Comment by calummoore** [comment]
This looks good, you took from before #71, right? If so, let's publish ash main. I.e. we want to make sure we don't include the AST stuff on the non-beta release as it's not currently deployed.

**Comment by mateuszmlc** [comment]
Yes, I built on top of commits from the npm version v0.3.23, so without the features that are not usable yet. I'll clean this up and resolve conflicts

**Comment by mateuszmlc** [comment]
To be clear, I don't know yet if this fixes the user's issue

**Comment by calummoore** [comment]
We've gotten into a bit of a mixed up state (my fault for merging in the changes to main before we had fully migrated). Going forward, merging to `main` should be only for things that are ready to be published (and we can CI that). I've created a beta branch, which will be for pending changes (which will also be CI'd).

I have taken `beta` from the current `main` (with the AST changes). We can then merge this PR into `main`, which would revert the AST changes. We should update `beta` with this change before merging into main.

We can then publish this change as version `0.3.24`. Make sense?

**Review by calummoore — APPROVED** [review]

**Comment by mateuszmlc** [comment]
Makes sense. Does the same apply for the other repositories?

Do you need me to change anything on this branch? Should I add the revert commit for the AST here?

**Comment by calummoore** [comment]
> Should I change the target branch to beta then? And we pull from beta to main, then revert changes that are not ready.

Yes, let's do that

**Comment by mateuszmlc** [comment]
Changed base branch to beta.

**Pull request merged**
