### PR TITLE
Add array and map fields

### PR DESCRIPTION
**Pull request by mateuszmlc**
Before merging this we need to merge https://github.com/polybase/polylang/pull/44, publish the npm package for it and update the version for @polybase/polylang in package.json

### CODE REVIEW

**Review by calummoore — APPROVED** [review]

**Comment by calummoore** [comment]
Once you've published `@polybase/polylang` do you want to publish this as a patch release. You should use `yarn lerna publish` at the root to publish.

**Comment by calummoore** [comment]
Will leave this unmerged until you've updated @polybase/polylang here.

**Comment by calummoore** [comment]
Now this is approved you should actually be able to merge it yourself when ready. 👍

**Comment by calummoore** [comment]
We should also update the docs (changelog and the section related to collection fns): https://github.com/polybase/docs

**Review by calummoore — APPROVED** [review]

**Comment by mateuszmlc** [comment]
> We should also update the docs (changelog and the section related to collection fns): https://github.com/polybase/docs

Should I make that change?

**Pull request merged**
