### PR TITLE
Allow querying by collection record fields

### PR DESCRIPTION
**Pull request by mateuszmlc**

### CODE REVIEW

**Comment by calummoore** [comment]
Could we have an client E2E test for this?

**Comment by mateuszmlc** [comment]
> Could we have an client E2E test for this?

We could, but they would be duplicates of what we have on the backend. Maybe we could instead test that the right requests are being sent and mock the responses?

**Comment by calummoore** [comment]
Yeah, it is a bit of duplication, but the client E2E tests are designed to fail if the contract with the server changes. If we mock the response, and the server spec changes we won't get a test failure. I agree we need to be careful about duplication, but I think in this case it's worthwhile.

**Comment by mateuszmlc** [comment]
Added a test 👍

**Review by calummoore — APPROVED** [review]

**Pull request merged**
