### PR TITLE
ENG-501: Add support for `PublicKey` arrays - added test, polylang

### PR DESCRIPTION
**Pull request by timmyjose**
This is PR 2 of the feature, ENG-501 - allow array of PublicKey.

Changes made:
  * Added test.

Depends on: https://github.com/polybase/polylang/pull/76

### CODE REVIEW

**Comment by calummoore** [comment]
@timmyjose How did you test that this works without the change to polylang being released to npm? Did you manually copy over the files? (thinking about this more from how we can improve this process).

**Comment by timmyjose** [comment]
> @timmyjose How did you test that this works without the change to polylang being released to npm? Did you manually copy over the files? (thinking about this more from how we can improve this process).

@calummoore  Yes, that's right! I did a a`yarn pack`, and copied over the `polybase-polylang-v0.4.11.tgz` file into polybase/client, and pointed it like so in the `package.json` file:

```
  "dependencies": {
    ...
    "@polybase/polylang": "./polybase-polylang-v0.4.11.tgz",
    ...
  }

```

Strangely enough, something like `file:...` did not work (with relative/absolute paths).

I did a similar thing while testing the `explorer` - bundle both polylang and polybase/client as packs and placing it inside the repo.

**Comment by calummoore** [comment]
Cool, so doing some digging you can actually use `npm link`: 

In Library A:

a. First, ensure library A is prepared for npm usage. You should have a package.json in place with a name and version.

b. In the directory of library A, run the command npm link. This creates a symbolic link in the global node_modules directory to library A.

In Library B:

a. Run the command npm link A, replacing "A" with the name you specified for library A in its package.json. This creates a symbolic link from your local node_modules to the global one for library A.

b. Now, if you run npm install, it will also install the dependencies of library A, and since we've linked it locally, it should use the latest code available.

Then run `npm unlink` when you're done.

**Comment by timmyjose** [comment]
@calummoore That's actually a nice solution! Manually bundling files is error-prone and tiresome.

**Comment by timmyjose** [comment]
Hey @calummoore, just a quick question - you mentioned on the `polylang` PR that the merge to `main` would create `beta` versions of the npm packages. Is there a specific site where they're pushed, or is it npm.io? I checked on the npm.io site, but I cannot see a beta version yet.

**Comment by timmyjose** [comment]
Updated and tested with `polylang v0.4.12-beta.102`. Also added the `yarn.lock` file into the PR. `yarn` e2e tests passing locally with this setup.

**Comment by calummoore** [comment]
Cool, the CI tests are not running because you forked the repo and so no actual push has occurred on this repo yet. In future, you can just create a branch on the main repo (as you have write permission, and not just an external user).

Can you re-create the branch on the main repo?

**Comment by calummoore** [comment]
> Ah, I see. Thanks for pointing that out! I will recreate the PR directly on the main branch itself.

Just to be clear, you would be creating a branch in this repo `eng-501-allow-arrays-for-public-keys` from main, add your commits, and then raise a new PR against main.

> P.S: I presume this does not apply to docs, but this will apply to explorer as well, right?

In general, that's the approach you should take, but there are no tests in explorer right now, so we can just merge from your fork this time. Next time you can just create the branch locally.

**Comment by timmyjose** [comment]
@calummoore Crystal clear! :+1:

**Comment by timmyjose** [comment]
Replaced by: https://github.com/polybase/polybase-ts/pull/133

**Pull request closed without merging**
